# Generated by Django 4.2.1 on 2023-05-16 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+573168456558'. Hasta 16 dígitos permitidos.", regex='^\\+?1?\\d{9,16}$')])),
                ('genre', models.CharField(max_length=15)),
                ('suffix', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
